repos:
  - repo: local
    hooks:
      - id: ocamlformat
        name: ocamlformat
        language: system
        entry: opam exec -- ocamlformat --inplace
        files: \.(ml|mli)$
      - id: docs
        name: docs
        language: system
        entry: make doc
        pass_filenames: false
        always_run: true
