#! /usr/bin/env bash
#
# Set up opam and install opam packages required to build the documentation.
# Like setup-opam but adds --with-doc to pull in odoc.
#
# This is used by the CI lint_docs job.
#
set -eu

eval "$(opam env)"

# Set up the opam repo (skip if already done, e.g. from a restored cache).
if ! opam repo list | grep -q '^github\b'; then
  opam repo add --all-switches -k git \
    github https://github.com/ocaml/opam-repository.git
  opam repo remove default
fi

opam install --deps-only --with-doc -y \
  ./yamlx.opam
