#! /usr/bin/env bash
#
# Run afl-fuzz.
# For best output, run in the foreground in a dedicated console and pass
# the argument [1-6]
#
set -eu

# Options suggested by afl-fuzz and allowing us to move on
#export AFL_DEBUG=1
export AFL_SKIP_CPUFREQ=1
export AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1

target=../_build/default/fuzz/fuzz.exe

run_one() {
  # requires the program to be afl-instrumented; see Makefile
  afl-fuzz -i seeds$i -o findings$i -- "$target" @@
}

case "$1" in
  "")
    # messy output
    for i in $(seq 1 6); do
      run_one &
    done
    ;;
  1|2|3|4|5|6)
    i=$1
    run_one
    ;;
  *)
    echo "out of range [1-6]: $1"
    exit 1
    ;;
esac
